config/routes.rb
SimuladorUniversidade::Application.routes.draw do

  root :to => 'pessoas#index'

  resources :pessoas
  resources :contatos
  resources :enderecos

end

app/models/contato.rb
# encoding: UTF-8
class Contato < ActiveRecord::Base
	self.table_name = "contatos"

	attr_accessible :pessoa_id, :pessoa, :telefone, :email

	belongs_to :pessoa, class_name: "Pessoa", foreign_key: :pessoa_id

end

app/models/endereco.rb
# encoding: UTF-8
class Endereco < ActiveRecord::Base
	self.table_name = "enderecos"

	attr_accessible :pessoa_id, :pessoa, :rua, :numero, :complemento, :cidade, :uf, :cep

	belongs_to :pessoa, class_name: "Pessoa", foreign_key: :pessoa_id

end

app/models/pessoa.rb
# encoding: UTF-8
class Pessoa < ActiveRecord::Base
	self.table_name = "pessoas"

	attr_accessible :professor, :matricula, :cpf, :nome, :carga_horaria

	has_many :contatos, class_name: "Contato", foreign_key: :pessoa_id
	has_many :enderecos, class_name: "Endereco", foreign_key: :pessoa_id

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController

	before_filter :menu_ativo

	def index
		@contatos = Contato.all
	end

	def show
		@contato = Contato.find_by_id(params[:id])
	end

	def new
		@contato = Contato.new
		@pessoas = Pessoa.all
	end

	def edit
		@contato = Contato.find_by_id(params[:id])
		@pessoas = Pessoa.all
	end

	def create
		@contato = Contato.new(params[:contato])

		if @contato.save
			redirect_to @contato
		else
			render action: "new"
		end
	end

	def update
		@contato = Contato.find_by_id(params[:id])

		if @contato.update_attributes(params[:contato])
			redirect_to @contato
		else
			render action: "edit"
		end
	end

	def destroy
		@contato = Contato.find_by_id(params[:id])
		@contato.destroy

		redirect_to contatos_url 
	end

	private

	def menu_ativo
		@menu_ativo = "Contatos"
	end
end

app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController

	before_filter :menu_ativo

	def index
		@enderecos = Endereco.all
	end

	def show
		@endereco = Endereco.find_by_id(params[:id])
	end

	def new
		@endereco = Endereco.new
		@pessoas = Pessoa.all
	end

	def edit
		@endereco = Endereco.find_by_id(params[:id])
		@pessoas = Pessoa.all
	end

	def create
		@endereco = Endereco.new(params[:endereco])

		if @endereco.save
			redirect_to @endereco
		else
			render action: "new"
		end
	end

	def update
		@endereco = Endereco.find_by_id(params[:id])

		if @endereco.update_attributes(params[:endereco])
			redirect_to @endereco
		else
			render action: "edit"
		end
	end

	def destroy
		@endereco = Endereco.find_by_id(params[:id])
		@endereco.destroy

		redirect_to enderecos_url 
	end

	private

	def menu_ativo
		@menu_ativo = "Enderecos"
	end
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController

	before_filter :menu_ativo

	def index
		@pessoas = Pessoa.all
	end

	def show
		@pessoa = Pessoa.find_by_id(params[:id])
	end

	def new
		@pessoa = Pessoa.new
	end

	def edit
		@pessoa = Pessoa.find_by_id(params[:id])
	end

	def create
		@pessoa = Pessoa.new(params[:pessoa])

		if @pessoa.save
			redirect_to @pessoa
		else
			render action: "new"
		end
	end

	def update
		@pessoa = Pessoa.find_by_id(params[:id])

		if @pessoa.update_attributes(params[:pessoa])
			redirect_to @pessoa
		else
			render action: "edit"
		end
	end

	def destroy
		@pessoa = Pessoa.find_by_id(params[:id])
		@pessoa.destroy

		redirect_to pessoas_url 
	end

	private

	def menu_ativo
		@menu_ativo = "Pessoas"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contatos/_form.html.erb
<% if @pessoas %>
	<%= form_for @contato , html:{style: "margin: 10px;"} do |f| %>
		<div class="form-group">
			<%= f.label :pessoa %>
			<%= f.select :pessoa_id, @pessoas.map{ |e| [e.nome.humanize, e.id]} %>
		</div>
		<div class="form-group">
			<%= f.label :telefone %>
			<%= f.text_field :telefone %>
		</div>
		<div class="form-group">
			<%= f.label :email %>
			<%= f.text_field :email %>
		</div>
		
		<%= f.submit "Salvar", class: "btn btn-success" %>
		<%= link_to "Cancelar", contatos_path, class: "btn btn-danger" %>
	<% end %>
<% else %>
	<div class="sem_registros" style='margin: 5px;'><%= "Não há pessoas cadastradas" %></div>
<% end %>

app/views/contatos/edit.html.erb
<div class="menu">
	<%= render '/menu' %>
</div>

<%= render 'form' %>

app/views/contatos/index.html.erb
<div class="menu">
	<%= render '/menu' %>
</div>
<%= link_to I18n.t('palavras.novo_registro'), new_contato_path, class: "btn btn-success", style: "float: right; margin: 5px;" %>
<% if @contatos.any? %>
	<table class="table table-striped">
		<tr>
			<th><%= Contato.human_attribute_name(:pessoa) %></th>
			<th><%= Contato.human_attribute_name(:telefone) %></th>
			<th><%= Contato.human_attribute_name(:email) %></th>
		</tr>
		<% @contatos.each do |contato| %>
			<tr>
				<td><%= link_to contato.pessoa.nome.humanize, contato %></td>
				<td><%= contato.telefone %></td>
				<td><%= contato.email %></td>
			</tr>
		<% end %>
	</table>
<% else %>
	<div class="sem_registros" style='margin: 5px;'><%= I18n.t('palavras.sem_registros') %></div>
<% end %>

app/views/contatos/new.html.erb
<div class="menu">
	<%= render '/menu' %>
</div>

<%= render 'form' %>

app/views/contatos/show.html.erb
<div class="menu">
	<%= render '/menu' %>
</div>
<%= link_to "Editar", edit_contato_path(@contato), class: "btn btn-primary", style: "float: right; margin: 5px;" %>
<%= link_to "Excluir", contato_path(@contato), method: :delete, confirm: "Tem certeza que deseja excluir?", class: "btn btn-danger", style: "float: right; margin: 5px;" %>
<%= link_to I18n.t('palavras.novo_registro'), new_contato_path, class: "btn btn-success", style: "float: right; margin: 5px;" %>

<div style="margin: 5px;">
	<div><%= Contato.human_attribute_name(:pessoa) %>: <%= @contato.pessoa.nome.humanize %></div>
	<div><%= Contato.human_attribute_name(:telefone) %>: <%= @contato.telefone %></div>
	<div><%= Contato.human_attribute_name(:email) %>: <%= @contato.email %></div>
</div>		

app/views/enderecos/_form.html.erb
<% if @pessoas %>
	<%= form_for @endereco , html:{style: "margin: 10px;"} do |f| %>
		<div class="form-group">
			<%= f.label :pessoa %>
			<%= f.select :pessoa_id, @pessoas.map{ |e| [e.nome.humanize, e.id]} %>
		</div>
		<div class="form-group">
			<%= f.label :rua %>
			<%= f.text_field :rua %>
		</div>
		<div class="form-group">
			<%= f.label :numero %>
			<%= f.text_field :numero %>
		</div>
		<div class="form-group">
			<%= f.label :complemento %>
			<%= f.text_field :complemento %>
		</div>
		<div class="form-group">
			<%= f.label :cidade %>
			<%= f.text_field :cidade %>
		</div>
		<div class="form-group">
			<%= f.label :uf %>
			<%= f.text_field :uf %>
		</div>
		<div class="form-group">
			<%= f.label :cep %>
			<%= f.text_field :cep %>
		</div>
		<%= f.submit "Salvar", class: "btn btn-success" %>
		<%= link_to "Cancelar", enderecos_path, class: "btn btn-danger" %>
	<% end %>
<% else %>
	<div class="sem_registros" style='margin: 5px;'><%= "Não há pessoas cadastradas" %></div>
<% end %>

app/views/enderecos/edit.html.erb
<div class="menu">
	<%= render '/menu' %>
</div>

<%= render 'form' %>

app/views/enderecos/index.html.erb
<div class="menu">
	<%= render '/menu' %>
</div>
<%= link_to I18n.t('palavras.novo_registro'), new_endereco_path, class: "btn btn-success", style: "float: right; margin: 5px;" %>
<% if @enderecos.any? %>
	<table class="table table-striped">
		<tr>
			<th><%= Endereco.human_attribute_name(:pessoa) %></th>
			<th><%= Endereco.human_attribute_name(:rua) %></th>
			<th><%= Endereco.human_attribute_name(:numero) %></th>
			<th><%= Endereco.human_attribute_name(:complemento) %></th>
			<th><%= Endereco.human_attribute_name(:cidade) %></th>
			<th><%= Endereco.human_attribute_name(:uf) %></th>
			<th><%= Endereco.human_attribute_name(:cep) %></th>
		</tr>
		<% @enderecos.each do |endereco| %>
			<tr>
				<td><%= link_to endereco.pessoa.nome.humanize, endereco %></td>
				<td><%= endereco.rua %></td>
				<td><%= endereco.numero %></td>
				<td><%= endereco.complemento %></td>
				<td><%= endereco.cidade %></td>
				<td><%= endereco.uf %></td>
				<td><%= endereco.cep %></td>
			</tr>
		<% end %>
	</table>
<% else %>
	<div class="sem_registros" style='margin: 5px;'><%= I18n.t('palavras.sem_registros') %></div>
<% end %>

app/views/enderecos/new.html.erb
<div class="menu">
	<%= render '/menu' %>
</div>

<%= render 'form' %>

app/views/enderecos/show.html.erb
<div class="menu">
	<%= render '/menu' %>
</div>
<%= link_to "Editar", edit_endereco_path(@endereco), class: "btn btn-primary", style: "float: right; margin: 5px;" %>
<%= link_to "Excluir", endereco_path(@endereco), method: :delete, confirm: "Tem certeza que deseja excluir?", class: "btn btn-danger", style: "float: right; margin: 5px;" %>
<%= link_to I18n.t('palavras.novo_registro'), new_endereco_path, class: "btn btn-success", style: "float: right; margin: 5px;" %>

<div style="margin: 5px;">
	<div><%= Endereco.human_attribute_name(:pessoa) %>: <%= @endereco.pessoa.nome.humanize %></div>
	<div><%= Endereco.human_attribute_name(:rua) %>: <%= @endereco.rua %></div>
	<div><%= Endereco.human_attribute_name(:numero) %>: <%= @endereco.numero %></div>
	<div><%= Endereco.human_attribute_name(:complemento) %>: <%= @endereco.complemento %></div>
	<div><%= Endereco.human_attribute_name(:cidade) %>: <%= @endereco.cidade %></div>
	<div><%= Endereco.human_attribute_name(:uf) %>: <%= @endereco.uf %></div>
	<div><%= Endereco.human_attribute_name(:cep) %>: <%= @endereco.cep %></div>
</div>		

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimuladorUniversidade</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pessoas/_form.html.erb
<%= form_for @pessoa , html:{style: "margin: 10px;"} do |f| %>
	<div class="form-group">
		<%= f.label :nome %>
		<%= f.text_field :nome %>
	</div>
	<div class="form-group">
		<%= f.label :matricula %>
		<%= f.text_field :matricula %>
	</div>
	<div class="form-group">
		<%= f.label :cpf %>
		<%= f.text_field :cpf %>
	</div>
	<div class="form-group">
		<%= f.label :professor %>
		<%= f.check_box :professor, style: 'margin-top: -10px;' %>
	</div>
	<div class="form-group">
		<%= f.label :carga_horaria %>
		<%= f.text_field :carga_horaria %>
	</div>
	<%= f.submit "Salvar", class: "btn btn-success" %>
	<%= link_to "Cancelar", pessoas_path, class: "btn btn-danger" %>
<% end %>

app/views/pessoas/edit.html.erb
<div class="menu">
	<%= render '/menu' %>
</div>

<%= render 'form' %>

app/views/pessoas/index.html.erb
<div class="menu">
	<%= render '/menu' %>
</div>
<%= link_to I18n.t('palavras.novo_registro'), new_pessoa_path, class: "btn btn-success", style: "float: right; margin: 5px;" %>
<% if @pessoas.any? %>
	<table class="table table-striped">
		<tr>
			<th><%= Pessoa.human_attribute_name(:nome) %></th>
			<th><%= Pessoa.human_attribute_name(:matricula) %></th>
			<th><%= Pessoa.human_attribute_name(:cpf) %></th>
			<th><%= Pessoa.human_attribute_name(:professor) %></th>
			<th><%= Pessoa.human_attribute_name(:carga_horaria) %></th>
		</tr>
		<% @pessoas.each do |pessoa| %>
			<tr>
				<td><%= link_to pessoa.nome.humanize, pessoa %></td>
				<td><%= pessoa.matricula %></td>
				<td><%= pessoa.cpf %></td>
				<td><%= pessoa.professor? ? image_tag('certo.png') : image_tag('errado.png') %></td>
				<td><%= pessoa.carga_horaria %></td>
			</tr>
		<% end %>
	</table>
<% else %>
	<div class="sem_registros" style='margin: 5px;'><%= I18n.t('palavras.sem_registros') %></div>
<% end %>

app/views/pessoas/new.html.erb
<div class="menu">
	<%= render '/menu' %>
</div>

<%= render 'form' %>

app/views/pessoas/show.html.erb
<div class="menu">
	<%= render '/menu' %>
</div>
<%= link_to "Editar", edit_pessoa_path(@pessoa), class: "btn btn-primary", style: "float: right; margin: 5px;" %>
<%= link_to "Excluir", pessoa_path(@pessoa), method: :delete, confirm: "Tem certeza que deseja excluir?", class: "btn btn-danger", style: "float: right; margin: 5px;" %>
<%= link_to I18n.t('palavras.novo_registro'), new_pessoa_path, class: "btn btn-success", style: "float: right; margin: 5px;" %>

<div style="margin: 5px;">
	<div style="font-weight: bold; margin-top: 20px;">Dados pessoais</div>
	<div><%= Pessoa.human_attribute_name(:nome) %>: <%= @pessoa.nome.humanize %></div>
	<div><%= Pessoa.human_attribute_name(:matricula) %>: <%= @pessoa.matricula %></div>
	<div><%= Pessoa.human_attribute_name(:cpf) %>: <%= @pessoa.cpf %></div>
	<div><%= Pessoa.human_attribute_name(:professor) %>: <%= @pessoa.professor? ? image_tag('certo.png') : image_tag('errado.png') %></div>
	<div><%= Pessoa.human_attribute_name(:carga_horaria) %>: <%= @pessoa.carga_horaria %></div>
</div>		

<% if @pessoa.contatos.any? %>
	<div style="margin: 5px; margin-top: 20px;">
		<div style="font-weight: bold;">Contatos</div>
		<% @pessoa.contatos.each do |contato| %>
			<div><%= Contato.human_attribute_name(:telefone) %>: <%= contato.telefone %></div>
			<div><%= Contato.human_attribute_name(:email) %>: <%= contato.email %></div>
		<% end %>
	</div>
<% end %>

<% if @pessoa.enderecos.any? %>
	<div style="margin: 5px;">
		<div style="font-weight: bold; margin-top: 20px;">Endereços</div>
		<% @pessoa.enderecos.each do |endereco| %>
			<div><%= Endereco.human_attribute_name(:rua) %>: <%= endereco.rua %></div>
			<div><%= Endereco.human_attribute_name(:numero) %>: <%= endereco.numero %></div>
			<div><%= Endereco.human_attribute_name(:complemento) %>: <%= endereco.complemento %></div>
			<div><%= Endereco.human_attribute_name(:cidade) %>: <%= endereco.cidade %></div>
			<div><%= Endereco.human_attribute_name(:uf) %>: <%= endereco.uf %></div>
			<div><%= Endereco.human_attribute_name(:cep) %>: <%= endereco.cep %></div>
		<% end %>
	</div>
<% end %>